version: "1.0"

services:

  postgres:
    image: docker.io/postgres:15
    container_name: sales_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/db:/docker-entrypoint-initdb.d
    networks:
      - saas-network
  rabbitmq:
    image: docker.io/rabbitmq:3-management
    container_name: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    env:
      - .env
    networks:
      - saas-network
  data-worker:
    build: ./data-worker-service
    container_name: data-worker-container
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - .env
    networks:
      - saas-network
    
  data-init:
    build: ./data-init
    container_name: data-init-container
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - data_ready:/ready
    networks:
      - saas-network

  data-generator:
    build: ./data-source-service
    container_name: data-source-container
    depends_on:
      - postgres
      - data-init
      - rabbitmq
      - data-worker
    volumes:
      - ./data-source-service:/app
      - data_ready:/ready
    env_file:
      - .env
    networks:
      - saas-network

  model-training:
    build: ./model-training-service
    container_name: model-training-container
    depends_on:
      - postgres
      - data-init
      - mlflow
    volumes:
      - ./model-training-service:/app
      - ./models:/models
      - data_ready:/ready
    env_file:
      - .env
    networks:
      - saas-network

  ml-service-worker:
    build: ./ml-worker-service
    container_name: ml-worker-container
    depends_on:
      - postgres
      - data-init
    volumes:
      - ./models:/models
      - data_ready:/ready
    env_file:
      - .env
    networks:
      - saas-network
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    container_name: mlflow-server
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
    volumes:
      - ./mlflow:/mlflow
  
  drift-detector:
    build: ./drift-detector-service
    container_name: drift-detector
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - saas-network

volumes:
  postgres_data:
  data_ready:

networks:
  saas-network:
    driver: bridge